test/Makefile: cache passing test results, to avoid re-run tedium.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -46,7 +46,7 @@ ifeq ($(CXX),)
 $(error Could not find crunchc++)
 endif
 
-cases := $(filter-out checks.sh,$(wildcard [-a-z]*))
+cases := $(filter-out checks.sh,$(filter-out rename-case.sh,$(wildcard [-a-z]*)))
 
 LIBCRUNCH := $(realpath $(dir $(THIS_MAKEFILE))/../lib/libcrunch_preload.so)
 
@@ -63,76 +63,104 @@ INCLUDE_MK_INC = `if test -e $(dir $(realpath $(THIS_MAKEFILE)))/$*/mk.inc; then
 default: checkall
 
 checkall: $(patsubst %,checkrun-%,$(cases))
+.PRECIOUS: $(patsubst %,%/check-stamp,$(cases))
+$(warning cases are $(cases))
+
+RERUN_TESTS_ON_CHANGE := $(LIBCRUNCH) $(shell find $(dir $(THIS_MAKEFILE))/../frontend | grep '\.cmxs$$' )
 
 # Some cases are expected to fail, i.e. generate libcrunch "check failed" stats.
 # Note that bounds errors never do this. HMM. Soon, type errors might not either.
-checkrun-fail-bounds-type-%:
+checkrun-fail-bounds-type-%: fail-bounds-type-%/check-stamp
+	true # remembered pass of fail-bounds-type-$*
+fail-bounds-type-%/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	@echo "expected-fail case is fail-bounds-type-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-bounds-type-$* 1>$$out 2>$$err && \
 		. ./checks.sh && tail -n26 "$$err" | \
-		    match "       failed otherwise" '[1-9][0-9]*' >/dev/null || \
+		    match "       failed otherwise" '[1-9][0-9]*' >/dev/null && \
+		    touch "$@" || \
 		(tail -n26 $$err; false)
-checkrun-fail-bounds-%:
+checkrun-fail-bounds-%: fail-bounds-%/check-stamp
+	true # remembered pass of fail-bounds-$*
+fail-bounds-%/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	@echo "expected-fail case is fail-bounds-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-bounds-$* 1>$$out 2>$$err && \
 		. ./checks.sh && tail -n26 "$$err" | \
-		    match "out-of-bounds pointers created" '[1-9][0-9]*' >/dev/null || \
+		    match "out-of-bounds pointers created" '[1-9][0-9]*' >/dev/null && \
+		    touch "$@" || \
 		(tail -n26 $$err; false)
 
 # Some cases are expected to fail, i.e. generate libcrunch "check failed" stats.
-checkrun-fail-%:
+checkrun-fail-%: fail-%/check-stamp
+	true # remembered pass of fail-$*
+fail-%/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	@echo "expected-fail case is fail-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-$* 1>$$out 2>$$err && \
 		. ./checks.sh && tail -n26 "$$err" | \
-		    match "       failed otherwise" '[1-9][0-9]*' >/dev/null || \
+		    match "       failed otherwise" '[1-9][0-9]*' >/dev/null && \
+		    touch "$@" || \
 		(tail -n26 $$err; false)
-		
+
+# some cases are ignored
+checkrun-ignore-%:
+	true # remembered pass of ignore-$*
 # Some cases are expected to abort the program (assertion failed, segfault, etc.)
-checkrun-abort-%:
-	@echo "expected-fail case is fail-$*" && \
-	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
-	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
-	if $(MAKE) cleanrun-abort-$* 1>$$out 2>$$err; then false; else true; fi
-		
+checkrun-abort-%: abort-%/check-stamp
+	true # remembered pass of abort-$*
+abort-%/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "expected-fail case is abort-$*" && \
+	out=$$( echo -n "fout is " 1>&2; mktemp | tee /dev/stderr ) && \
+	err=$$( echo -n "ferr is " 1>&2; mktemp | tee /dev/stderr ) && \
+	if $(MAKE) cleanrun-abort-$* 1>$$out 2>$$err; then false; else touch "$@"; fi
+
 # Some cases are expected to succeed without liballocs being involved.
-checkrun-noquery-%:
+checkrun-noquery-%: noquery-%/check-stamp
+	true # remembered pass of noquery-$*
+noquery-%/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	@echo "no-query case is noquery-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	if $(MAKE) cleanrun-noquery-$* 1>$$out 2>$$err && \
-           ! grep '^queries handled.* [1-9]+[0-9]*$$' $$err; then true; else false; fi
+           ! grep '^queries handled.* [1-9]+[0-9]*$$' $$err; then touch "$@"; else false; fi
 
 # Bounds cases might not report passed type checks
-checkrun-bounds-%:
+checkrun-bounds-%: bounds-%/check-stamp
+	true # remembered pass of bounds-$*
+bounds-%/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	@echo "case is bounds-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-bounds-$* 1>$$out 2>$$err && \
 		. ./checks.sh && tail -n26 "$$err" | \
-		    match "out-of-bounds pointers created" '0' >/dev/null || \
+		    match "out-of-bounds pointers created" '0' >/dev/null && \
+		    touch "$@" || \
 		(tail -n26 $$err; false)
 
 # Trap bounds cases should report OOB pointers
-checkrun-trap-bounds-%:
+checkrun-trap-bounds-%: trap-bounds-%/check-stamp
+	true # remembered pass of trap-bounds-$*
+trap-bounds-%/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	@echo "case is trap-bounds-$*" && \
-	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
-	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
+	out=$$( echo -n "tout is " 1>&2; mktemp | tee /dev/stderr ) && \
+	err=$$( echo -n "terr is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-trap-bounds-$* 1>$$out 2>$$err && \
 		. ./checks.sh && tail -n26 "$$err" | \
-		    match "out-of-bounds pointers created" '[1-9][0-9]*' >/dev/null || \
+		    match "out-of-bounds pointers created" '[1-9][0-9]*' >/dev/null && \
+		    touch "$@" || \
 		(tail -n26 $$err; false)
 
 # Most test cases should output a libcrunch summary in which 
 # -- zero or more checks passed (trivially or by lazy typing)
 # -- zero checks aborted
 # -- zero checks failed
-checkrun-%:
+checkrun-%: %/check-stamp
+	true # remembered pass of $*
+%/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	@echo "case is $*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
@@ -140,29 +168,39 @@ checkrun-%:
 		. ./checks.sh && tail -n26 "$$err" | \
 		    match "       nontrivially passed" '[1-9][0-9]*' | \
 		    match "       failed inside"        '0' | \
-		    match "       failed otherwise"     '0' >/dev/null || \
+		    match "       failed otherwise"     '0' >/dev/null && \
+		    touch "$@" || \
 		(tail -n26 $$err; false)
 
 # Some cases are special and require only an exit status of zero
-checkrun-hello: 
-	$(MAKE) cleanrun-hello >/dev/null 2>&1
-checkrun-hello-c++: 
-	$(MAKE) cleanrun-hello-c++ >/dev/null 2>&1
-checkrun-hello-errno: 
-	$(MAKE) cleanrun-hello-errno >/dev/null 2>&1
-checkrun-hello-qualified-char:
-	$(MAKE) cleanrun-hello-qualified-char >/dev/null 2>&1
-checkrun-random:
-	$(MAKE) cleanrun-random >/dev/null 2>&1
-checkrun-pointer-degree:
-	$(MAKE) cleanrun-pointer-degree >/dev/null 2>&1
-checkrun-bounds-simple:
-	$(MAKE) cleanrun-bounds-simple >/dev/null 2>&1
-checkrun-bounds-diff:
-	$(MAKE) cleanrun-bounds-diff >/dev/null 2>&1
+checkrun-hello: hello/check-stamp
+hello/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	$(MAKE) cleanrun-hello >/dev/null 2>&1 && touch "$@"
+checkrun-hello-c++: hello-c++/check-stamp
+hello-c++/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	$(MAKE) cleanrun-hello-c++ >/dev/null 2>&1 && touch "$@"
+checkrun-hello-errno: hello-errno/check-stamp
+hello-errno/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	$(MAKE) cleanrun-hello-errno >/dev/null 2>&1 && touch "$@"
+checkrun-hello-qualified-char: hello-qualified-char/check-stamp
+hello-qualified-char/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	$(MAKE) cleanrun-hello-qualified-char >/dev/null 2>&1 && touch "$@"
+checkrun-random: random/check-stamp
+random/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	$(MAKE) cleanrun-random >/dev/null 2>&1 && touch "$@"
+checkrun-pointer-degree: pointer-degree/check-stamp
+pointer-degree/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	$(MAKE) cleanrun-pointer-degree >/dev/null 2>&1 && touch "$@"
+checkrun-bounds-simple: bounds-simple/check-stamp
+bounds-simple/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	$(MAKE) cleanrun-bounds-simple >/dev/null 2>&1 && touch "$@"
+checkrun-bounds-diff: bounds-diff/check-stamp
+bounds-diff/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	$(MAKE) cleanrun-bounds-diff >/dev/null 2>&1 && touch "$@"
 
 # Some cases are special and have their own matching criteria
-checkrun-lazy-typing:
+checkrun-lazy-typing: lazy-typing/check-stamp
+lazy-typing/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	@echo "case is lazy-typing" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
@@ -170,7 +208,8 @@ checkrun-lazy-typing:
 		. ./checks.sh && tail -n26 "$$err" | \
 		    match "of which did lazy heap type assignment" '[1-9][0-9]*' | \
 		    match "       failed inside"        '0' | \
-		    match "       failed otherwise"     '0' >/dev/null || \
+		    match "       failed otherwise"     '0' >/dev/null && \
+		    touch "$@" || \
 		(tail -n26 $$err; false)
 
 _onlyrun-%:
@@ -201,11 +240,6 @@ gdbcleanrun-%:
 
 clean-%:
 	$(MAKE) -C "$*" $(INCLUDE_MK_INC) -f $(realpath $(THIS_MAKEFILE)) clean
-
-default:
-	for case in $(cases); do \
-            $(MAKE) run-$$case; \
-        done
 
 # generic clean rule that we can run from test dirs too (with $(MAKE) -f ../Makefile)
 clean: # (delete anything whose name is a prefix of a .c file's and doesn't contain a dot)
