Support multi-frontend testing.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -3,6 +3,8 @@ CFLAGS += -g3 -gstrict-dwarf -std=c99 -fno-eliminate-unused-debug-types -O2
 CFLAGS += -DUSE_STARTUP_BRK
 
 THIS_MAKEFILE := $(lastword $(MAKEFILE_LIST))
+TESTDIR := $(realpath $(dir $(THIS_MAKEFILE)))
+$(warning TESTDIR is $(TESTDIR))
 
 export CFLAGS
 
@@ -16,43 +18,12 @@ export ALLOCSITES_BASE
 export LIBCRUNCH_BASE := $(realpath $(dir $(THIS_MAKEFILE))/..)
 export LIBCRUNCH_ALWAYS_PRINT_EXIT_SUMMARY := 1
 
-# To support differential testing against implementations, each test
-# is allowed to provide a list of the frontends it wants to test.
-# It should do this in mk.inc.
-# What does run-% or checkrun-% do in these circumstances?
-# What do we do with the %/check-stamp files?
-# Where do the builds live?
-# First step: each test is built and run in a FRONTEND dir.
-FRONTEND := crunchcc
-
-CRUNCHCC ?= $(LIBCRUNCH_BASE)/frontend/c/bin/crunchcc
-#$(warning in Makefile, CRUNCHCC is $(CRUNCHCC))
-CRUNCHCXX ?= $(LIBCRUNCH_BASE)/frontend/c++/bin/crunchc++
-# use lazy expansion for these, so that changes to crunchcc get reflected
-CC = $(CRUNCHCC)
-#$(warning in Makefile, CC is $(CC))
-CXX = $(CRUNCHCXX)
-export CRUNCHCC
-export CRUNCHCXX
-export CC
-export CXX
-
-export CFLAGS += -I$(realpath $(dir $(THIS_MAKEFILE)))/../include -I$(LIBALLOCS)/include
-export LDFLAGS += -L$(LIBALLOCS)/lib
-
 ifneq ($(USE_FAKE_LIBUNWIND),)
 CFLAGS += -fno-omit-frame-pointer
 CXXFLAGS += -fno-omit-frame-pointer
 LIBUNWIND_LDLIBS :=
 else
 LIBUNWIND_LDLIBS := -lunwind -lunwind-`uname -m` 
-endif
-
-ifeq ($(CC),)
-$(error Could not find crunchcc)
-endif
-ifeq ($(CXX),)
-$(error Could not find crunchc++)
 endif
 
 cases := $(filter-out checks.sh,$(filter-out rename-case.sh,$(wildcard [-a-z]*)))
@@ -71,11 +42,84 @@ INCLUDE_MK_INC = `if test -e $(dir $(realpath $(THIS_MAKEFILE)))/$*/mk.inc; then
 
 default: checkalltests
 
-checkalltests: $(patsubst %,checkrun-%,$(cases))
-.PRECIOUS: $(patsubst %,%/$(FRONTEND)/check-stamp,$(cases))
 ifeq ($(MAKECMDGOAL),)
 $(warning cases are $(cases))
 endif
+
+# If we don't have a frontend in mind, loop over all frontends
+frontends = c c++ clang
+ifeq ($(FRONTEND),)
+checkalltests:
+	for f in c clang c++; do \
+		$(MAKE) FRONTEND=$$f checkalltests || break; \
+	done
+else
+# everything else in the whole rest of the file assumes we have a unique FRONTEND.
+DEFAULT_CC = $(LIBCRUNCH_BASE)/frontend/$(FRONTEND)/bin/cc
+ifeq ($(CC),cc)
+CC := $(DEFAULT_CC)
+endif
+ifeq ($(CC),)
+CC := $(DEFAULT_CC)
+endif
+$(warning in $(MAKEFILE_LIST), CC is $(CC))
+DEFAULT_CXX = $(LIBCRUNCH_BASE)/frontend/$(FRONTEND)/bin/c++
+ifeq ($(CXX),g++) # i.e. make's "default" CXX value
+CXX := $(DEFAULT_CXX)
+endif
+ifeq ($(CXX),)
+CXX := $(DEFAULT_CXX)
+endif
+$(warning in $(MAKEFILE_LIST), CXX is $(CXX))
+export CC
+export CXX
+export CFLAGS += -I$(realpath $(dir $(THIS_MAKEFILE)))/../include -I$(LIBALLOCS)/include
+export LDFLAGS += -L$(LIBALLOCS)/lib
+
+# We want to filter the list of cases, to include only those
+# relevant to the current FRONTEND.
+# What defines a frontend? One idea: it's a directory in frontend/.
+# It's partly a language thing, but not always.
+# The common case is C-language tests,
+# where we might want "c, clang" but occasionally just "c".
+# Some, like Fortran, might want "Fortran".
+# Use a kernel-style makevar solution:
+# But that's not enough, because each frontend (say the CIL frontend)
+# may define multiple compilers (crunchcc, crunchxcc, ...).
+
+# Give each test a chance to say something about its frontends
+#$(foreach c,$(cases),-include $(c)/frontend.mk)
+
+-include */frontend.mk
+
+# This could do either
+# CASES_$(FRONTEND) += ourselves # for each fe
+# or
+# FRONTENDS_$(case) += < list of frontends >
+# -- which?
+# Common-case rules are: assume C language, so frontends "c" and "clang".
+# For all cases which don't define a frontend.mk, add to CASES_c and CASES_clang.
+fe_cases := $(foreach c,$(cases),$(notdir $(realpath $(dir $(wildcard $(TESTDIR)/$(c)/frontend.mk)))))
+no_fe_cases := $(filter-out $(fe_cases),$(cases))
+$(warning fe_cases is $(fe_cases))
+$(warning no_fe_cases is $(no_fe_cases))
+CASES_c += $(no_fe_cases)
+CASES_clang += $(no_fe_cases)
+
+fcases := $(filter $(CASES_$(FRONTEND)),$(cases))
+$(warning frontend $(FRONTEND), fcases is $(fcases))
+
+# We can also set CC in mk.inc -- clearly this conflicts with the frontend
+# setting. Check this: if we've specified CC and our frontend is not "c",
+# something's wrong.
+ifneq ($(CC),$(DEFAULT_CC))
+ifneq ($(FRONTEND),c)
+$(error "Specified CC as $(CC), but frontend is $(FRONTEND)")
+endif
+endif
+
+checkalltests: $(patsubst %,checkrun-%,$(fcases))
+.PRECIOUS: $(patsubst %,%/$(FRONTEND)/check-stamp,$(fcases))
 
 RERUN_TESTS_ON_CHANGE := $(LIBCRUNCH) $(shell find $(dir $(THIS_MAKEFILE))/../frontend | grep '\.cmxs$$' )
 
@@ -84,7 +128,7 @@ RERUN_TESTS_ON_CHANGE := $(LIBCRUNCH) $(shell find $(dir $(THIS_MAKEFILE))/../fr
 checkrun-fail-bounds-type-%: fail-bounds-type-%/$(FRONTEND)/check-stamp
 	true # remembered pass of fail-bounds-type-$*
 fail-bounds-type-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "expected-fail case is fail-bounds-type-$*" && \
+	@echo "frontend $(FRONTEND), expected-fail case is fail-bounds-type-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-bounds-type-$* 1>$$out 2>$$err && \
@@ -95,7 +139,7 @@ fail-bounds-type-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 checkrun-fail-bounds-%: fail-bounds-%/$(FRONTEND)/check-stamp
 	true # remembered pass of fail-bounds-$*
 fail-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "expected-fail case is fail-bounds-$*" && \
+	@echo "frontend $(FRONTEND), expected-fail case is fail-bounds-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-bounds-$* 1>$$out 2>$$err && \
@@ -108,7 +152,7 @@ fail-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 checkrun-fail-%: fail-%/$(FRONTEND)/check-stamp
 	true # remembered pass of fail-$*
 fail-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "expected-fail case is fail-$*" && \
+	@echo "frontend $(FRONTEND), expected-fail case is fail-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-$* 1>$$out 2>$$err && \
@@ -124,7 +168,7 @@ checkrun-ignore-%:
 checkrun-abort-%: abort-%/$(FRONTEND)/check-stamp
 	true # remembered pass of abort-$*
 abort-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "expected-fail case is abort-$*" && \
+	@echo "frontend $(FRONTEND), expected-fail case is abort-$*" && \
 	out=$$( echo -n "fout is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "ferr is " 1>&2; mktemp | tee /dev/stderr ) && \
 	if $(MAKE) cleanrun-abort-$* 1>$$out 2>$$err; then false; else touch "$@"; fi
@@ -133,7 +177,7 @@ abort-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 checkrun-noquery-%: noquery-%/$(FRONTEND)/check-stamp
 	true # remembered pass of noquery-$*
 noquery-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "no-query case is noquery-$*" && \
+	@echo "frontend $(FRONTEND), no-query case is noquery-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	if $(MAKE) cleanrun-noquery-$* 1>$$out 2>$$err && \
@@ -143,7 +187,7 @@ noquery-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 checkrun-softbound-%: softbound-%/$(FRONTEND)/check-stamp
 	true # remembered pass of softbound-$*
 softbound-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "case is softbound-$*" && \
+	@echo "frontend $(FRONTEND), case is softbound-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	if $(MAKE) cleanrun-softbound-$* 1>$$out 2>$$err && \
@@ -155,7 +199,7 @@ softbound-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 checkrun-bounds-%: bounds-%/$(FRONTEND)/check-stamp
 	true # remembered pass of bounds-$*
 bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "case is bounds-$*" && \
+	@echo "frontend $(FRONTEND), case is bounds-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-bounds-$* 1>$$out 2>$$err && \
@@ -167,7 +211,7 @@ bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 checkrun-trap-bounds-%: trap-bounds-%/$(FRONTEND)/check-stamp
 	true # remembered pass of trap-bounds-$*
 trap-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "case is trap-bounds-$*" && \
+	@echo "frontend $(FRONTEND), case is trap-bounds-$*" && \
 	out=$$( echo -n "tout is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "terr is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-trap-bounds-$* 1>$$out 2>$$err && \
@@ -183,7 +227,7 @@ trap-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 checkrun-%: %/$(FRONTEND)/check-stamp
 	true # remembered pass of $*
 %/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "case is $*" && \
+	@echo "frontend $(FRONTEND), case is $*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-$* 1>$$out 2>$$err && \
@@ -223,7 +267,7 @@ bounds-diff/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 # Some cases are special and have their own matching criteria
 checkrun-lazy-typing: lazy-typing/$(FRONTEND)/check-stamp
 lazy-typing/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "case is lazy-typing" && \
+	@echo "frontend $(FRONTEND), case is lazy-typing" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-lazy-typing 1>$$out 2>$$err && \
@@ -251,7 +295,8 @@ build-%:
 	$(MAKE) -C "$*"/$(FRONTEND) $(INCLUDE_MK_INC) -f ../../Makefile "$*" 
 
 run-%:
-	$(MAKE) build-$* && ( $(MAKE) -C "$*"/$(FRONTEND) $(INCLUDE_MK_INC) -f ../../Makefile _onlyrun-$* )
+	$(MAKE) build-$*
+	$(MAKE) -C "$*"/$(FRONTEND) $(INCLUDE_MK_INC) -f ../../Makefile _onlyrun-$*
 
 cleanbuild-%:
 	$(MAKE) clean-$*
@@ -269,11 +314,19 @@ gdbcleanrun-%:
 	$(MAKE) clean-$*
 	$(MAKE) gdbrun-$*
 
+endif # end assuming we have FRONTEND
+
 clean-%:
-	if [ -d "$*"/$(FRONTEND) ]; then $(MAKE) -C "$*"/$(FRONTEND) $(INCLUDE_MK_INC) -f $(realpath $(THIS_MAKEFILE)) clean; fi
+	if [ -z "$(FRONTEND)" ]; then frontends="$(frontends)"; else frontends=$(FRONTEND); fi; \
+	for f in $$frontends; do \
+		if [ -d "$*"/$$f ]; then \
+			$(MAKE) -C "$*"/$$f $(INCLUDE_MK_INC) -f $(realpath $(THIS_MAKEFILE)) clean; \
+			rm -f "$*"/$$f/"$*"; \
+		fi; \
+	done
 
 # generic clean rule that we can run from test dirs too (with $(MAKE) -f ../Makefile)
-clean: # (delete anything whose name is a prefix of a .c file's and doesn't contain a dot)
+clean: $(foreach c,$(cases),clean-$(c)) # (delete anything whose name is a prefix of a .c file's and doesn't contain a dot)
 	rm -f $(filter-out .,$(patsubst %.c,%,$(shell find -name '*.c')))
 	rm -f $(filter-out .,$(patsubst %.cc,%,$(shell find -name '*.cc')))
 	find -name '*.cil.*'  -o -name '*.i' -o -name '*.o' -o -name '*.s' -o -name '*.allocs' | xargs rm -f
