test: overhaul Makefile so that each case is run with both a FRONTEND and a CONFIG. This will allow tests to be shared between frontends, particularly useful in the cases of c and cilpp.

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -47,34 +47,42 @@ INCLUDE_MK_INC = `if test -e $(dir $(realpath $(THIS_MAKEFILE)))/$*/mk.inc; then
 default: checkalltests
 
 ifeq ($(MAKECMDGOAL),)
-$(warning cases are $(cases))
+#$(warning cases are $(cases))
 endif
 
-# If we don't have a frontend in mind, loop over all frontends
-frontends = c c++ clang
-ifeq ($(FRONTEND),)
+# If we don't have a frontend in mind, loop over all frontends.
+# What about configs? Each test defines one or more configs in which it's supposed to pass.
+frontends = c c++ cilpp clang
+configs = default pb Sb x # Pb mb Mb tb Tb sb
+ifeq ($(FRONTEND)$(CONFIG),)
 checkalltests:
-	for f in c clang c++; do \
-		$(MAKE) FRONTEND=$$f checkalltests || break; \
+	for f in $(frontends); do \
+		for c in $(configs); do \
+			$(MAKE) FRONTEND=$$f CONFIG=$$c checkalltests || break 2; \
+		done; \
 	done
 else
-# everything else in the whole rest of the file assumes we have a unique FRONTEND.
-DEFAULT_CC = $(LIBCRUNCH_BASE)/frontend/$(FRONTEND)/bin/cc
+FRONTEND ?= c
+CONFIG ?= default
+# everything else in the whole rest of the file assumes we have a unique FRONTEND and CONFIG
+# set CC according to our config
+DEFAULT_CC = $(LIBCRUNCH_BASE)/frontend/$(FRONTEND)/bin/$(CONFIG:default=)cc
 ifeq ($(CC),cc)
 CC := $(DEFAULT_CC)
 endif
 ifeq ($(CC),)
 CC := $(DEFAULT_CC)
 endif
-$(warning in $(MAKEFILE_LIST), CC is $(CC))
-DEFAULT_CXX = $(LIBCRUNCH_BASE)/frontend/$(FRONTEND)/bin/c++
-ifeq ($(CXX),g++) # i.e. make's "default" CXX value
+#$(warning in $(MAKEFILE_LIST), CC is $(CC))
+# set CXX according to our config
+DEFAULT_CXX = $(LIBCRUNCH_BASE)/frontend/$(FRONTEND)/bin/$(CONFIG:default=)c++
+ifeq ($(CXX),g++) # i.e. GNU make's "default" CXX value
 CXX := $(DEFAULT_CXX)
 endif
 ifeq ($(CXX),)
 CXX := $(DEFAULT_CXX)
 endif
-$(warning in $(MAKEFILE_LIST), CXX is $(CXX))
+#$(warning in $(MAKEFILE_LIST), CXX is $(CXX))
 export CC
 export CXX
 export CFLAGS += -I$(realpath $(dir $(THIS_MAKEFILE)))/../include -I$(LIBALLOCS)/include
@@ -91,7 +99,7 @@ export LDFLAGS += -L$(LIBALLOCS)/lib
 # But that's not enough, because each frontend (say the CIL frontend)
 # may define multiple compilers (crunchcc, crunchxcc, ...).
 
-# Give each test a chance to say something about its frontends
+# Give each test a chance to say something about its frontends and configs
 #$(foreach c,$(cases),-include $(c)/frontend.mk)
 
 -include */frontend.mk
@@ -101,38 +109,53 @@ export LDFLAGS += -L$(LIBALLOCS)/lib
 # or
 # FRONTENDS_$(case) += < list of frontends >
 # -- which?
-# Common-case rules are: assume C language, so frontends "c" and "clang".
+explicit_fe_cases := $(foreach c,$(cases),$(notdir $(realpath $(dir $(wildcard $(TESTDIR)/$(c)/frontend.mk)))))
+no_explicit_fe_cases := $(filter-out $(explicit_fe_cases),$(cases))
+#$(warning explicit_fe_cases is $(explicit_fe_cases))
+#$(warning no_explicit_fe_cases is $(no_explicit_fe_cases))
+# Common-case rules are:
+# - assume C language, so frontends "c" and "clang".
+# - assume default config
 # For all cases which don't define a frontend.mk, add to CASES_c and CASES_clang.
-fe_cases := $(foreach c,$(cases),$(notdir $(realpath $(dir $(wildcard $(TESTDIR)/$(c)/frontend.mk)))))
-no_fe_cases := $(filter-out $(fe_cases),$(cases))
-$(warning fe_cases is $(fe_cases))
-$(warning no_fe_cases is $(no_fe_cases))
-CASES_c += $(no_fe_cases)
-CASES_clang += $(no_fe_cases)
+CASES_c += $(no_explicit_fe_cases)
+CASES_clang += $(no_explicit_fe_cases)
+CASES_CONFIG_default += $(no_explicit_fe_cases)
 
+# This frontend cases, and this config cases
 fcases := $(filter $(CASES_$(FRONTEND)),$(cases))
-$(warning frontend $(FRONTEND), fcases is $(fcases))
+ccases := $(filter $(CASES_CONFIG_$(CONFIG)),$(cases))
+fccases := $(filter $(CASES_CONFIG_$(CONFIG)),$(fcases))
+$(info frontend $(FRONTEND), config $(CONFIG))
+#$(info fcases is $(fcases))
+#$(info ccases is $(ccases))
+$(info fccases is $(fccases))
 
-# We can also set CC in mk.inc -- clearly this conflicts with the frontend
-# setting. Check this: if we've specified CC and our frontend is not "c",
-# something's wrong.
+# We used to specify "config" by setting CC in mk.inc.
+# Now we have frontend.mk do it.
+# Big question: should be support multiple configs per test,
+# or just a single one?
+# E.g. a subset of bounds tests will run on Sb or b.
+# It needs to be multiple configs, because we have so many bounds configs.
+# If we've specified CC, it should match our frontend/config.
 ifneq ($(CC),$(DEFAULT_CC))
-ifneq ($(FRONTEND),c)
-$(error "Specified CC as $(CC), but frontend is $(FRONTEND)")
-endif
+$(error "Specified CC as $(CC), but frontend $(FRONTEND) and config $(CONFIG) makes $(DEFAULT_CC)")
 endif
 
-checkalltests: $(patsubst %,checkrun-%,$(fcases))
-.PRECIOUS: $(patsubst %,%/$(FRONTEND)/check-stamp,$(fcases))
+# Our default target: do a checkrun of all cases for the current frontend.
+# Do we also have a "current config"?
+checkalltests: $(patsubst %,checkrun-%,$(fccases))
+# Our stamp files should not be removed by make, even though they are not explicit targets
+.PRECIOUS: $(patsubst %,%/$(FRONTEND)+$(CONFIG)/check-stamp,$(fccases))
 
+# List of everything which, if changed, should prompt re-running tests.
 RERUN_TESTS_ON_CHANGE := $(LIBCRUNCH) $(shell find $(dir $(THIS_MAKEFILE))/../frontend | grep '\.cmxs$$' )
 
 # Some cases are expected to fail, i.e. generate libcrunch "check failed" stats.
 # Note that bounds errors never do this. HMM. Soon, type errors might not either.
-checkrun-fail-bounds-type-%: fail-bounds-type-%/$(FRONTEND)/check-stamp
+checkrun-fail-bounds-type-%: fail-bounds-type-%/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of fail-bounds-type-$*
-fail-bounds-type-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), expected-fail case is fail-bounds-type-$*" && \
+fail-bounds-type-%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), expected-fail case is fail-bounds-type-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-bounds-type-$* 1>$$out 2>$$err && \
@@ -140,10 +163,10 @@ fail-bounds-type-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 		    match "       failed otherwise" '[1-9][0-9]*' >/dev/null && \
 		    touch "$@" || \
 		(tail -n26 $$err; false)
-checkrun-fail-bounds-%: fail-bounds-%/$(FRONTEND)/check-stamp
+checkrun-fail-bounds-%: fail-bounds-%/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of fail-bounds-$*
-fail-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), expected-fail case is fail-bounds-$*" && \
+fail-bounds-%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), expected-fail case is fail-bounds-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-bounds-$* 1>$$out 2>$$err && \
@@ -153,10 +176,10 @@ fail-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 		(tail -n26 $$err; false)
 
 # Some cases are expected to fail, i.e. generate libcrunch "check failed" stats.
-checkrun-fail-%: fail-%/$(FRONTEND)/check-stamp
+checkrun-fail-%: fail-%/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of fail-$*
-fail-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), expected-fail case is fail-$*" && \
+fail-%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), expected-fail case is fail-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-fail-$* 1>$$out 2>$$err && \
@@ -169,29 +192,29 @@ fail-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 checkrun-ignore-%:
 	true # remembered pass of ignore-$*
 # Some cases are expected to abort the program (assertion failed, segfault, etc.)
-checkrun-abort-%: abort-%/$(FRONTEND)/check-stamp
+checkrun-abort-%: abort-%/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of abort-$*
-abort-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), expected-fail case is abort-$*" && \
+abort-%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), expected-fail case is abort-$*" && \
 	out=$$( echo -n "fout is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "ferr is " 1>&2; mktemp | tee /dev/stderr ) && \
 	if $(MAKE) cleanrun-abort-$* 1>$$out 2>$$err; then false; else touch "$@"; fi
 
 # Some cases are expected to succeed without liballocs being involved.
-checkrun-noquery-%: noquery-%/$(FRONTEND)/check-stamp
+checkrun-noquery-%: noquery-%/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of noquery-$*
-noquery-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), no-query case is noquery-$*" && \
+noquery-%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), no-query case is noquery-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	if $(MAKE) cleanrun-noquery-$* 1>$$out 2>$$err && \
            ! grep '^queries handled.* [1-9]\+[0-9]*$$' $$err; then touch "$@"; else false; fi
 
 # SoftBound should also never call liballocs
-checkrun-softbound-%: softbound-%/$(FRONTEND)/check-stamp
+checkrun-softbound-%: softbound-%/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of softbound-$*
-softbound-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), case is softbound-$*" && \
+softbound-%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), case is softbound-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	if $(MAKE) cleanrun-softbound-$* 1>$$out 2>$$err && \
@@ -200,10 +223,10 @@ softbound-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
                 ! grep 'calls to __fetch_bounds:.* [1-9]\+[0-9]*$$' $$err; then touch "$@"; else false; fi
 
 # Bounds cases might not report passed type checks
-checkrun-bounds-%: bounds-%/$(FRONTEND)/check-stamp
+checkrun-bounds-%: bounds-%/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of bounds-$*
-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), case is bounds-$*" && \
+bounds-%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), case is bounds-$*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-bounds-$* 1>$$out 2>$$err && \
@@ -212,10 +235,10 @@ bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 		(tail -n26 $$err; false)
 
 # Trap bounds cases should report OOB pointers
-checkrun-trap-bounds-%: trap-bounds-%/$(FRONTEND)/check-stamp
+checkrun-trap-bounds-%: trap-bounds-%/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of trap-bounds-$*
-trap-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), case is trap-bounds-$*" && \
+trap-bounds-%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), case is trap-bounds-$*" && \
 	out=$$( echo -n "tout is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "terr is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-trap-bounds-$* 1>$$out 2>$$err && \
@@ -228,10 +251,10 @@ trap-bounds-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 # -- zero or more checks passed (trivially or by lazy typing)
 # -- zero checks aborted
 # -- zero checks failed
-checkrun-%: %/$(FRONTEND)/check-stamp
+checkrun-%: %/$(FRONTEND)+$(CONFIG)/check-stamp
 	true # remembered pass of $*
-%/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), case is $*" && \
+%/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), case is $*" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-$* 1>$$out 2>$$err && \
@@ -243,35 +266,35 @@ checkrun-%: %/$(FRONTEND)/check-stamp
 		(tail -n32 $$err; false)
 
 # Some cases are special and require only an exit status of zero
-checkrun-hello: hello/$(FRONTEND)/check-stamp
-hello/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+checkrun-hello: hello/$(FRONTEND)+$(CONFIG)/check-stamp
+hello/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	$(MAKE) cleanrun-hello >/dev/null 2>&1 && touch "$@"
-checkrun-hello-c++: hello-c++/$(FRONTEND)/check-stamp
-hello-c++/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+checkrun-hello-c++: hello-c++/$(FRONTEND)+$(CONFIG)/check-stamp
+hello-c++/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	$(MAKE) cleanrun-hello-c++ >/dev/null 2>&1 && touch "$@"
-checkrun-hello-errno: hello-errno/$(FRONTEND)/check-stamp
-hello-errno/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+checkrun-hello-errno: hello-errno/$(FRONTEND)+$(CONFIG)/check-stamp
+hello-errno/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	$(MAKE) cleanrun-hello-errno >/dev/null 2>&1 && touch "$@"
-checkrun-hello-qualified-char: hello-qualified-char/$(FRONTEND)/check-stamp
-hello-qualified-char/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+checkrun-hello-qualified-char: hello-qualified-char/$(FRONTEND)+$(CONFIG)/check-stamp
+hello-qualified-char/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	$(MAKE) cleanrun-hello-qualified-char >/dev/null 2>&1 && touch "$@"
-checkrun-random: random/$(FRONTEND)/check-stamp
-random/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+checkrun-random: random/$(FRONTEND)+$(CONFIG)/check-stamp
+random/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	$(MAKE) cleanrun-random >/dev/null 2>&1 && touch "$@"
-checkrun-pointer-degree: pointer-degree/$(FRONTEND)/check-stamp
-pointer-degree/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+checkrun-pointer-degree: pointer-degree/$(FRONTEND)+$(CONFIG)/check-stamp
+pointer-degree/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	$(MAKE) cleanrun-pointer-degree >/dev/null 2>&1 && touch "$@"
-checkrun-bounds-simple: bounds-simple/$(FRONTEND)/check-stamp
-bounds-simple/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+checkrun-bounds-simple: bounds-simple/$(FRONTEND)+$(CONFIG)/check-stamp
+bounds-simple/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	$(MAKE) cleanrun-bounds-simple >/dev/null 2>&1 && touch "$@"
-checkrun-bounds-diff: bounds-diff/$(FRONTEND)/check-stamp
-bounds-diff/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+checkrun-bounds-diff: bounds-diff/$(FRONTEND)+$(CONFIG)/check-stamp
+bounds-diff/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
 	$(MAKE) cleanrun-bounds-diff >/dev/null 2>&1 && touch "$@"
 
 # Some cases are special and have their own matching criteria
-#checkrun-lazy-typing: lazy-typing/$(FRONTEND)/check-stamp
-XXXdisabed-lazy-typing/$(FRONTEND)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
-	@echo "frontend $(FRONTEND), case is lazy-typing" && \
+#checkrun-lazy-typing: lazy-typing/$(FRONTEND)+$(CONFIG)/check-stamp
+XXXdisabed-lazy-typing/$(FRONTEND)+$(CONFIG)/check-stamp: $(RERUN_TESTS_ON_CHANGE)
+	@echo "frontend $(FRONTEND), config $(CONFIG), case is lazy-typing" && \
 	out=$$( echo -n "out is " 1>&2; mktemp | tee /dev/stderr ) && \
 	err=$$( echo -n "err is " 1>&2; mktemp | tee /dev/stderr ) && \
 	$(MAKE) cleanrun-lazy-typing 1>$$out 2>$$err && \
@@ -295,12 +318,12 @@ vpath %.cpp ..
 
 # These are the main targets
 build-%:
-	mkdir -p "$*"/$(FRONTEND)
-	$(MAKE) -C "$*"/$(FRONTEND) $(INCLUDE_MK_INC) -f ../../Makefile "$*" 
+	mkdir -p "$*"/$(FRONTEND)+$(CONFIG)
+	$(MAKE) -C "$*"/$(FRONTEND)+$(CONFIG) $(INCLUDE_MK_INC) -f ../../Makefile "$*" 
 
 run-%:
 	$(MAKE) build-$*
-	$(MAKE) -C "$*"/$(FRONTEND) $(INCLUDE_MK_INC) -f ../../Makefile _onlyrun-$*
+	$(MAKE) -C "$*"/$(FRONTEND)+$(CONFIG) $(INCLUDE_MK_INC) -f ../../Makefile _onlyrun-$*
 
 cleanbuild-%:
 	$(MAKE) clean-$*
@@ -311,8 +334,8 @@ cleanrun-%:
 	$(MAKE) run-$*
 
 gdbrun-%: # run the test case with itself as input
-	$(MAKE) -C "$*"/$(FRONTEND) $(INCLUDE_MK_INC) "$*"
-	$(MAKE) -C "$*"/$(FRONTEND) $(INCLUDE_MK_INC) -f ../../Makefile _onlygdbrun-$*
+	$(MAKE) -C "$*"/$(FRONTEND)+$(CONFIG) $(INCLUDE_MK_INC) "$*"
+	$(MAKE) -C "$*"/$(FRONTEND)+$(CONFIG) $(INCLUDE_MK_INC) -f ../../Makefile _onlygdbrun-$*
 
 gdbcleanrun-%:
 	$(MAKE) clean-$*
