Support negative offsets in objdump output.

diff --git a/dumpallocs/objdumpallocs b/dumpallocs/objdumpallocs
--- a/dumpallocs/objdumpallocs
+++ b/dumpallocs/objdumpallocs
@@ -111,6 +111,11 @@ echo "$objdump_output" > "$tmpfile"
 bytes_consumed=0
 
 while read address sym offset; do
+    # 0. skip blank lines
+    if [[ -z "${address}${sym}${offset}" ]]; then
+        continue
+    fi
+
     # Now use the power of objdump -S to get the source line for that alloc.
     # 1, Build a regexp that will re-locate the current alloc site.
     
@@ -126,7 +131,7 @@ while read address sym offset; do
     #context="$( echo "$objdump_output" | egrep -B30 "$regexp" )" #"
     #echo "context the slow way: $context" 1>&2
     # instead of this, use sed
-    next_chunk="$( tail -c+$(( $bytes_consumed + 1 )) "$tmpfile" | sed -r "/$regexp/ q" )"
+    next_chunk="$( tail -c+$(( $bytes_consumed + 1 )) "$tmpfile" 2>/dev/null | sed -r "/$regexp/ q" )"
     #echo "fast way, next chunk: $next_chunk" 1>&2
     bytes_consumed=$(( $bytes_consumed + $( echo "$next_chunk" | wc -c ) ))
     #echo "bytes_consumed is now $bytes_consumed" 1>&2
@@ -141,7 +146,7 @@ while read address sym offset; do
     # what we read next will be garbage, so grep for something that matches the pattern
     file_line_header="$( echo "$with_file_line_header" | egrep '^/.*:[0-9]+( \(discriminator [0-9]*\))?$' | head -n1 )"
     if [[ -z "$file_line_header" ]]; then 
-        echo "Warning: could not find source line for ${sym}+${offset}, skipping" 1>&2
+        echo "Warning: could not find source line for ${sym}${offset}, skipping" 1>&2
         echo "Context attempt was:"$'\n'"$with_file_line_header" 1>&2
         continue
     fi
@@ -154,7 +159,7 @@ while read address sym offset; do
     source_lines_count="$( echo "$source_lines" | wc -l )"
     # HACK: if we didn't get anything, make sure we output a 1-line interval anyway
     if [[ $source_lines_count -eq 0 ]]; then
-        echo "Warning: context for ${sym}+${offset} appears to contain zero source lines. Context follows." 1>&2
+        echo "Warning: context for ${sym}${offset} appears to contain zero source lines. Context follows." 1>&2
         echo "$source_lines" 1>&2
         source_lines_count=1
     fi
@@ -173,8 +178,8 @@ while read address sym offset; do
     sed -r 's/[^0-9a-zA-Z_]*([a-zA-Z0-9_ \*]+).*/\1/' | tr -s '[:blank:]' ' ' )" #"
     #echo "token: $token" 1>&2
     # 4a. We want the *return address*, not the site of the call per se. Fix this up.
-    instr_line_regexp='([0-9a-f]+)[[:blank:]]*<([^\+]+)(\+(0x[0-9a-f]+))?>.*'
-    next_line="$( tail -c+$(( $bytes_consumed + 1 )) "$tmpfile" | sed -rn "/^${instr_line_regexp}/ { s/$instr_line_regexp/\1\t\2\t\4/ ; p; q }" )"
+    instr_line_regexp='([0-9a-f]+)[[:blank:]]*<([^-\+]+)([-\+](0x[0-9a-f]+))?>.*'
+    next_line="$( tail -c+$(( $bytes_consumed + 1 )) "$tmpfile" 2>/dev/null | sed -rn "/^${instr_line_regexp}/ { s/$instr_line_regexp/\1\t\2\t\4/ ; p; q }" )"
     read return_addr return_addr_sym return_addr_offset <<<"$next_line"
     #return_addr_sym="$sym"
     #return_addr_offset="$offset"
@@ -198,6 +203,6 @@ while read address sym offset; do
             echo "<${return_addr_sym}+${return_addr_offset}> @${filename}:${line_number}"$'\t'"${token:-\$FAILED\$}"
             ;;
     esac
-done <<<"$( echo "$allocation_sites" | sed -r 's/\+(0x[0-9a-f]*)$/ \1/' )" #"
+done <<<"$( echo "$allocation_sites" | sed -r 's/([-\+]0x[0-9a-f]*)$/ \1/' )" #"
 
 rm -f "$tmpfile"
